### ISSUE TITLE
Histrogram not plotted with ggMarginal if the limits of the axes are widened

### ISSUE THREAD

**Issue by Sim19** [daattali/ggExtra#75]
Hi, 

I guess due to a recent update of the package, there are a few bugs now, which weren't there before.
I'd like to make the axes of my scatterplot symmetric. 
But when adding the histograms on the y and x axes with ggExtra:ggMarginal($GGPLOT, 'histogram'), the histogram of the axis that is enlarged the most, is not shown. Instead, two vertical bars are drawn (seemingly random).
When the limits of the axes in $GGPLOT are not changed, the plot is fine.

I last ran that exact code on the same data on June 23rd, 2017. Then, the histograms on the axes were just fine.

**Comment by crew102** [comment]
Can you provide a reproducible example of the bug you are seeing? In other words, can you provide some example code that results in the unwanted graph that you are getting?

**Comment by jonathan-g** [comment]
Here is a minimal reproducible case
```
library(tidyverse)
library(ggExtra)

df = tibble(x = rnorm(1000), y = rnorm(1000))

ggplot(df, aes(x = x, y = y)) + geom_point() %>% ggMarginal(type = 'histogram')
p1 = ggplot(df, aes(x = x, y = y)) + geom_point()
m1 = ggMarginal(p1, type = 'histogram')

print(m1)
```
![rplot02](https://user-images.githubusercontent.com/5304060/31926688-d13506ce-b855-11e7-9c0d-7ed66773ad11.png)
```
rx  = range(df$x)
ry = range(df$y)
r = c(min(rx, ry), max(rx,ry))
p2 = ggplot(df, aes(x = x, y = y)) + geom_point() + xlim(r) + ylim(r)
m2 = ggMarginal(p2, type = 'histogram')

print(m2)
```

![rplot](https://user-images.githubusercontent.com/5304060/31926685-ce040586-b855-11e7-81ff-08a093308d0a.png)

**Comment by jonathan-g** [comment]
P.S., If I do 
```
install_github('daattali/ggExtra', ref="v0.6")
```
Then the second plot comes out properly.

**Comment by daattali** [comment]
Thanks, this does look like a regression bug. Although it looks to me like only the y axis is affected, and not the x axis, do you agree?

Here is a more minimal example showing the problem (using your code but more minimal for debugging):

```
library(ggExtra)
library(ggplot2)

df <- data.frame(x = rnorm(1000), y = rnorm(1000))

p1 <- ggplot(df, aes(x = x, y = y)) + geom_point()
m1 <- ggMarginal(p1, type = 'histogram')
print(m1)

p2 <- p1 + xlim(-5, 5) + ylim(-5, 5)
m2 <- ggMarginal(p2, type = 'histogram')
print(m2)
```

**Comment by crew102** [comment]
Hmm, I wonder what is going on here. I'll take a look by week's end.

**Comment by jonathan-g** [comment]
I agree that it only seems to affect the y-axis. 

I like your more minimalist reproducible example. Nice chance for me learn about being more concise.

**Comment by daattali** [comment]
Eliminate any package that is not 100% necessary, and use as few variables as possible - use hardcoded values instead to make it clear exactly what's going on :) Makes it much easier to debug

**Comment by crew102** [comment]
I'm going to add a unit test to the the upcoming pr later today...forgot to do that before i pushed.

**Comment by daattali** [comment]
@Sim19 and @jonathan-g please make sure the fix works for you. You can thank @crew102

**Comment by DeLaRiva** [comment]
Hi, this issue isn't solved, right? At least for me it seems to be open?

**Comment by crew102** [comment]
Based on the color of the histograms in your example, it looks like you may be using an old version of ggExtra. Try updating it with `devtools::install_github("daattali/ggExtra")`.

**Comment by Futats** [comment]
I have the same issue DeLaRiva reported, even after updating using `devtools::install_github("daattali/ggExtra")`. 
It appears that `ggMarginal()` doesn't scale with `coord_cartesian()`, though it scales properly with `xlim()` and `ylim()`. Is this intentional?
 
Here's an addendum to the earlier example:

> df <- data.frame(x = rnorm(1000), y = rnorm(1000))
> 
> p1 <- ggplot(df, aes(x = x, y = y)) + geom_point() + ggtitle("xlim / ylim")
> m1 <- ggMarginal(p1, type = 'histogram')
> print(m1)
> 
> p2 <- p1 + xlim(-10, 10) + ylim(-10,10) + ggtitle("xlim / ylim")
> m2 <- ggMarginal(p2, type = 'histogram')
> print(m2)
> 
> p3 <- p1 + coord_cartesian(xlim = c(-10, 10), ylim = c(-10, 10)) + ggtitle("Coord_Cartesian")
> m3 <- ggMarginal(p3, type = 'histogram')
> print(m3)


![image](https://user-images.githubusercontent.com/42077756/43666867-781353ac-972a-11e8-8c27-6572038fd9dc.png)

**Comment by crew102** [comment]
It wasn't intentional, and is relatively easily fixed. The only question from my point of view is, whenever `coord_cartesian()` is used in the scatter plot, should the marginal plots be created using all of the data,  or only the data that is shown in the scatter plot?

From `?coord_cartesian`:

```r
# There are two ways of zooming the plot display: with scales or
# with coordinate systems.  They work in two rather different ways.

p <- ggplot(mtcars, aes(disp, wt)) +
  geom_point() +
  geom_smooth()
p

# Setting the limits on a scale converts all values outside the range to NA.
p + scale_x_continuous(limits = c(325, 500))

# Setting the limits on the coordinate system performs a visual zoom.
# The data is unchanged, and we just view a small portion of the original
# plot. Note how smooth continues past the points visible on this plot.
p + coord_cartesian(xlim = c(325, 500))
```

For example, if the user uses `coord_cartesian(xlim = c(5, 20))` in their scatter plot, should the marginal density plot look like this:

``` r
library(ggplot2)

p <- ggplot(mtcars) + geom_density(aes(mpg))

p + coord_cartesian(xlim = c(5, 20))
```

![](https://i.imgur.com/3WLZiKL.png)

...Or like this:

``` r

p + xlim(c(5, 20))
#> Warning: Removed 14 rows containing non-finite values (stat_density).
```

![](https://i.imgur.com/HLkIC5i.png)

I think the second choice will provide more intuitive output.
